import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ContactForm from "../../components/contact-form/contact-us/ContactForm";
import HeroSection from "../../components/contact-form/hero-section/HeroSection";
import ServicesComponent from "../../components/contact-form/services-component/ServicesComponent";
import CallToAction from "../../components/contact-form/call-to-action/CallToAction.component";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Include Manrope font */}
        <link
          href="https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <main className="relative overflow-hidden">
          <HeroSection />
          <ServicesComponent />
          <CallToAction />
          <ContactForm />
        </main>
      </body>
    </html>
  );
}
